services:
  db:
    image: postgres:15-alpine
    container_name: postgres_prod
    restart: always
    command:
      - postgres
      - -c
      - log_min_messages=warning
      - -c
      - log_statement=none
      - -c
      - log_min_duration_statement=1000
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    logging:
      driver: awslogs
      options:
        awslogs-region: ap-northeast-2
        awslogs-group: /kanban/prod/db
        awslogs-stream: postgres
        awslogs-create-group: 'true'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    image: 643766342252.dkr.ecr.ap-northeast-2.amazonaws.com/kanban-server:latest
    container_name: nest_api_prod
    restart: always
    env_file:
      - .env
    ports:
      - '3000:3000'
    environment:
      DB_HOST: db # 로컬 localhost 대신 서비스 이름 'db' 사용
      DB_PORT: 5432
      NODE_ENV: production
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
    depends_on:
      - db
    logging:
      driver: awslogs
      options:
        awslogs-region: ap-northeast-2
        awslogs-group: /kanban/prod/api
        awslogs-stream: api
        awslogs-create-group: 'true'
volumes:
  postgres_data:
